services:
  emag_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emag_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - API_PORT=8002
    ports:
      - "8002:8002"
    networks:
      - proxy

networks:
  proxy:
    external: true
